# Generated by Django 6.1 on 2026-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='budget_quote',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_timeline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('incorporated', 'Incorporated'), ('dpiit_recognized', 'DPIIT Recognized')], default='unregistered', max_length=20),
        ),
    ]
