# Generated by Django 6.1 on 2026-09-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_budget_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini')], max_length=20)),
                ('api_key', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='NoveltyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('likely_novel', 'Likely Novel'), ('similar_exists', 'Similar Solutions Exist'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=20)),
                ('similar_products', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novelty_check', to='core.application')),
            ],
        ),
    ]
