# Generated by Django 6.1 on 2026-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiproviderconfig_noveltycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
