# Generated by Django 5.2.17 on 2026-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_evaluation_score_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleupentry',
            name='adopted_count',
            field=models.IntegerField(default=0),
        ),
    ]
